namespace SM3DiagTool.Models;

public static class KnownDtcCodes
{
    public static readonly Dictionary<string, string> Descriptions = new()
    {
        // Powertrain - Fuel & Air Metering
        ["P0100"] = "Przeplywomierz powietrza (MAF) - awaria obwodu",
        ["P0101"] = "Przeplywomierz powietrza (MAF) - zakres/wydajnosc",
        ["P0102"] = "Przeplywomierz powietrza (MAF) - niski sygnal",
        ["P0103"] = "Przeplywomierz powietrza (MAF) - wysoki sygnal",
        ["P0104"] = "Przeplywomierz powietrza (MAF) - przerywany sygnal",
        ["P0105"] = "Czujnik cisnienia w kolektorze (MAP) - awaria obwodu",
        ["P0106"] = "Czujnik MAP - zakres/wydajnosc",
        ["P0107"] = "Czujnik MAP - niski sygnal",
        ["P0108"] = "Czujnik MAP - wysoki sygnal",
        ["P0110"] = "Czujnik temperatury powietrza dolotowego (IAT) - awaria",
        ["P0111"] = "Czujnik IAT - zakres/wydajnosc",
        ["P0112"] = "Czujnik IAT - niski sygnal",
        ["P0113"] = "Czujnik IAT - wysoki sygnal",
        ["P0115"] = "Czujnik temperatury plynu chlodniczego (ECT) - awaria",
        ["P0116"] = "Czujnik ECT - zakres/wydajnosc",
        ["P0117"] = "Czujnik ECT - niski sygnal",
        ["P0118"] = "Czujnik ECT - wysoki sygnal",
        ["P0120"] = "Czujnik pozycji przepustnicy (TPS) - awaria obwodu",
        ["P0121"] = "Czujnik TPS - zakres/wydajnosc",
        ["P0122"] = "Czujnik TPS - niski sygnal",
        ["P0123"] = "Czujnik TPS - wysoki sygnal",
        ["P0125"] = "Niewystarczajaca temp. chlodzenia dla sterowania paliwem",
        ["P0128"] = "Termostat - temp. chlodzenia ponizej progu regulacji",
        ["P0130"] = "Sonda lambda B1S1 - awaria obwodu",
        ["P0131"] = "Sonda lambda B1S1 - niskie napiecie",
        ["P0132"] = "Sonda lambda B1S1 - wysokie napiecie",
        ["P0133"] = "Sonda lambda B1S1 - wolna reakcja",
        ["P0134"] = "Sonda lambda B1S1 - brak aktywnosci",
        ["P0135"] = "Sonda lambda B1S1 - awaria grzalki",
        ["P0136"] = "Sonda lambda B1S2 - awaria obwodu",
        ["P0137"] = "Sonda lambda B1S2 - niskie napiecie",
        ["P0138"] = "Sonda lambda B1S2 - wysokie napiecie",
        ["P0139"] = "Sonda lambda B1S2 - wolna reakcja",
        ["P0140"] = "Sonda lambda B1S2 - brak aktywnosci",
        ["P0141"] = "Sonda lambda B1S2 - awaria grzalki",
        ["P0150"] = "Sonda lambda B2S1 - awaria obwodu",
        ["P0151"] = "Sonda lambda B2S1 - niskie napiecie",
        ["P0152"] = "Sonda lambda B2S1 - wysokie napiecie",
        ["P0153"] = "Sonda lambda B2S1 - wolna reakcja",
        ["P0154"] = "Sonda lambda B2S1 - brak aktywnosci",
        ["P0155"] = "Sonda lambda B2S1 - awaria grzalki",
        ["P0156"] = "Sonda lambda B2S2 - awaria obwodu",
        ["P0157"] = "Sonda lambda B2S2 - niskie napiecie",
        ["P0158"] = "Sonda lambda B2S2 - wysokie napiecie",
        ["P0160"] = "Sonda lambda B2S2 - brak aktywnosci",
        ["P0161"] = "Sonda lambda B2S2 - awaria grzalki",
        ["P0170"] = "Korekcja mieszanki B1 - awaria",
        ["P0171"] = "Mieszanka zbyt uboga - bank 1",
        ["P0172"] = "Mieszanka zbyt bogata - bank 1",
        ["P0173"] = "Korekcja mieszanki B2 - awaria",
        ["P0174"] = "Mieszanka zbyt uboga - bank 2",
        ["P0175"] = "Mieszanka zbyt bogata - bank 2",

        // Ignition System
        ["P0200"] = "Wtryskiwacz - awaria obwodu",
        ["P0201"] = "Wtryskiwacz cyl. 1 - awaria obwodu",
        ["P0202"] = "Wtryskiwacz cyl. 2 - awaria obwodu",
        ["P0203"] = "Wtryskiwacz cyl. 3 - awaria obwodu",
        ["P0204"] = "Wtryskiwacz cyl. 4 - awaria obwodu",
        ["P0205"] = "Wtryskiwacz cyl. 5 - awaria obwodu",
        ["P0206"] = "Wtryskiwacz cyl. 6 - awaria obwodu",
        ["P0207"] = "Wtryskiwacz cyl. 7 - awaria obwodu",
        ["P0208"] = "Wtryskiwacz cyl. 8 - awaria obwodu",
        ["P0215"] = "Elektrozawor odciecia paliwa - awaria",
        ["P0218"] = "Przegrzanie skrzyni biegow",
        ["P0219"] = "Przekroczenie obrotow silnika",
        ["P0220"] = "Czujnik TPS B - awaria obwodu",
        ["P0221"] = "Czujnik TPS B - zakres/wydajnosc",
        ["P0222"] = "Czujnik TPS B - niski sygnal",
        ["P0223"] = "Czujnik TPS B - wysoki sygnal",
        ["P0230"] = "Pompa paliwa - awaria obwodu pierwotnego",
        ["P0234"] = "Turbosprężarka - nadmierny boost",
        ["P0235"] = "Czujnik cisnienia doladowania - awaria",
        ["P0243"] = "Zawor sterujacy turbo (WGT) - awaria",
        ["P0245"] = "Zawor sterujacy turbo A - niski sygnal",
        ["P0246"] = "Zawor sterujacy turbo A - wysoki sygnal",
        ["P0251"] = "Pompa wtryskowa A (diesel) - awaria",

        // Misfire
        ["P0300"] = "Wypadanie zaplonow - losowe/wiele cylindrow",
        ["P0301"] = "Wypadanie zaplonow - cylinder 1",
        ["P0302"] = "Wypadanie zaplonow - cylinder 2",
        ["P0303"] = "Wypadanie zaplonow - cylinder 3",
        ["P0304"] = "Wypadanie zaplonow - cylinder 4",
        ["P0305"] = "Wypadanie zaplonow - cylinder 5",
        ["P0306"] = "Wypadanie zaplonow - cylinder 6",
        ["P0307"] = "Wypadanie zaplonow - cylinder 7",
        ["P0308"] = "Wypadanie zaplonow - cylinder 8",
        ["P0325"] = "Czujnik spalania stukowego B1 - awaria",
        ["P0326"] = "Czujnik spalania stukowego B1 - zakres",
        ["P0327"] = "Czujnik spalania stukowego B1 - niski sygnal",
        ["P0328"] = "Czujnik spalania stukowego B1 - wysoki sygnal",
        ["P0330"] = "Czujnik spalania stukowego B2 - awaria",
        ["P0335"] = "Czujnik polozenia walu korbowego (CKP) - awaria",
        ["P0336"] = "Czujnik CKP - zakres/wydajnosc",
        ["P0340"] = "Czujnik polozenia walu rozrzadu (CMP) A B1 - awaria",
        ["P0341"] = "Czujnik CMP A B1 - zakres/wydajnosc",
        ["P0345"] = "Czujnik CMP A B2 - awaria",
        ["P0350"] = "Cewka zaplonowa - awaria obwodu",
        ["P0351"] = "Cewka zaplonowa A - awaria obwodu",
        ["P0352"] = "Cewka zaplonowa B - awaria obwodu",
        ["P0353"] = "Cewka zaplonowa C - awaria obwodu",
        ["P0354"] = "Cewka zaplonowa D - awaria obwodu",

        // Emission Control
        ["P0400"] = "Uklad recyrkulacji spalin (EGR) - awaria",
        ["P0401"] = "EGR - niewystarczajacy przeplyw",
        ["P0402"] = "EGR - nadmierny przeplyw",
        ["P0403"] = "EGR - awaria obwodu sterujacego",
        ["P0404"] = "EGR - zakres/wydajnosc",
        ["P0410"] = "Uklad wtornego powietrza - awaria",
        ["P0411"] = "Uklad wtornego powietrza - nieprawidlowy przeplyw",
        ["P0420"] = "Katalizator B1 - sprawnosc ponizej progu",
        ["P0421"] = "Katalizator B1 - niska sprawnosc nagrzewania",
        ["P0430"] = "Katalizator B2 - sprawnosc ponizej progu",
        ["P0440"] = "EVAP - awaria ukladu",
        ["P0441"] = "EVAP - nieprawidlowy przeplyw oczyszczania",
        ["P0442"] = "EVAP - maly wyciek",
        ["P0443"] = "EVAP - zawor oczyszczania - awaria obwodu",
        ["P0446"] = "EVAP - zawor odpowietrzania - awaria obwodu",
        ["P0450"] = "EVAP - czujnik cisnienia - awaria",
        ["P0455"] = "EVAP - duzy wyciek",
        ["P0456"] = "EVAP - bardzo maly wyciek",

        // Speed/Idle Control
        ["P0500"] = "Czujnik predkosci pojazdu (VSS) - awaria",
        ["P0501"] = "Czujnik VSS - zakres/wydajnosc",
        ["P0505"] = "Sterowanie biegu jalowego - awaria",
        ["P0506"] = "Sterowanie biegu jalowego - obroty nizsze niz oczekiwane",
        ["P0507"] = "Sterowanie biegu jalowego - obroty wyzsze niz oczekiwane",
        ["P0510"] = "Czujnik polozenia przepustnicy zamknietej - awaria",
        ["P0520"] = "Czujnik cisnienia oleju - awaria obwodu",
        ["P0521"] = "Czujnik cisnienia oleju - zakres/wydajnosc",
        ["P0522"] = "Czujnik cisnienia oleju - niski sygnal",
        ["P0523"] = "Czujnik cisnienia oleju - wysoki sygnal",
        ["P0530"] = "Czujnik cisnienia czynnika chlodniczego AC - awaria",
        ["P0562"] = "Napiecie systemu - niskie",
        ["P0563"] = "Napiecie systemu - wysokie",

        // Transmission
        ["P0600"] = "Magistrala CAN - awaria komunikacji",
        ["P0601"] = "ECM - blad pamieci wewnetrznej (checksum)",
        ["P0602"] = "ECM - blad programowania",
        ["P0606"] = "ECM - blad procesora",
        ["P0615"] = "Przekaznik rozrusznika - awaria obwodu",
        ["P0625"] = "Pole generatora - awaria obwodu",
        ["P0627"] = "Pompa paliwa - awaria obwodu sterujacego",
        ["P0630"] = "VIN niezaprogramowany w ECM",
        ["P0685"] = "Przekaznik zasilania ECM - awaria obwodu",
        ["P0700"] = "Sterownik skrzyni biegow - awaria",
        ["P0705"] = "Czujnik zakresu skrzyni (TRS) - awaria obwodu",
        ["P0710"] = "Czujnik temp. oleju skrzyni (TFT) - awaria",
        ["P0715"] = "Czujnik predkosci turbiny - awaria",
        ["P0720"] = "Czujnik predkosci wyjsciowej - awaria",
        ["P0725"] = "Czujnik obrotow silnika (sygnal skrzyni) - awaria",
        ["P0730"] = "Nieprawidlowe przelozenie",
        ["P0731"] = "Bieg 1 - nieprawidlowe przelozenie",
        ["P0732"] = "Bieg 2 - nieprawidlowe przelozenie",
        ["P0733"] = "Bieg 3 - nieprawidlowe przelozenie",
        ["P0734"] = "Bieg 4 - nieprawidlowe przelozenie",
        ["P0740"] = "Sprzeglo blokujace - awaria obwodu",
        ["P0741"] = "Sprzeglo blokujace - nieprawidlowa praca",
        ["P0750"] = "Elektrozawor zmiany A - awaria",
        ["P0755"] = "Elektrozawor zmiany B - awaria",

        // Diesel Specific
        ["P0093"] = "Uklad paliwowy - duzy wyciek",
        ["P0087"] = "Cisnienie w szynie paliwowej za niskie",
        ["P0088"] = "Cisnienie w szynie paliwowej za wysokie",
        ["P0089"] = "Regulator cisnienia paliwa - wydajnosc",
        ["P0190"] = "Czujnik cisnienia szyny paliwowej - awaria",
        ["P0191"] = "Czujnik cisnienia szyny paliwowej - zakres",
        ["P0192"] = "Czujnik cisnienia szyny paliwowej - niski sygnal",
        ["P0193"] = "Czujnik cisnienia szyny paliwowej - wysoki sygnal",
        ["P0380"] = "Swiece zarowe - awaria obwodu",
        ["P0381"] = "Kontrolka swiee zarowych - awaria",
        ["P0401"] = "EGR - niewystarczajacy przeplyw",
        ["P2002"] = "Filtr czastek stalych (DPF) - sprawnosc ponizej progu",
        ["P2031"] = "Czujnik temperatury spalin B1 - awaria",
        ["P2032"] = "Czujnik temperatury spalin B1 - niski sygnal",
        ["P2033"] = "Czujnik temperatury spalin B1 - wysoki sygnal",
        ["P2080"] = "Czujnik temperatury spalin B1S2 - zakres",
        ["P2100"] = "Silnik przepustnicy - awaria obwodu",
        ["P2101"] = "Silnik przepustnicy - zakres/wydajnosc",
        ["P2122"] = "Czujnik pozycji pedalu gazu D - niski sygnal",
        ["P2123"] = "Czujnik pozycji pedalu gazu D - wysoki sygnal",
        ["P2127"] = "Czujnik pozycji pedalu gazu E - niski sygnal",
        ["P2128"] = "Czujnik pozycji pedalu gazu E - wysoki sygnal",
        ["P2138"] = "Czujniki pozycji pedalu gazu D/E - korelacja",
        ["P2146"] = "Grupa wtryskiwaczy A - awaria obwodu zasilania",
        ["P2149"] = "Grupa wtryskiwaczy B - awaria obwodu zasilania",
        ["P2187"] = "Mieszanka zbyt uboga na biegu jalowym B1",
        ["P2188"] = "Mieszanka zbyt bogata na biegu jalowym B1",
        ["P2263"] = "Turbosprężarka - nadmierny/niewystarczajacy boost",
        ["P242F"] = "Filtr DPF - ograniczenie/popioly",
        ["P244A"] = "Czujnik cisnienia roznicowego DPF - niski sygnal",
        ["P2452"] = "Czujnik cisnienia roznicowego DPF - awaria",
        ["P2453"] = "Czujnik cisnienia roznicowego DPF - zakres",
        ["P2454"] = "Czujnik cisnienia roznicowego DPF - niski sygnal",
        ["P2455"] = "Czujnik cisnienia roznicowego DPF - wysoki sygnal",
        ["P2BAD"] = "Czujnik NOx B1 - sygnal CAN",

        // Body
        ["B0001"] = "Sterownik modulu nadwozia - awaria wewnetrzna",
        ["B0010"] = "Czujnik zderzenia frontowego prawego - awaria",
        ["B0020"] = "Czujnik zderzenia frontowego lewego - awaria",
        ["B0050"] = "Czujnik zderzenia bocznego prawego - awaria",
        ["B0060"] = "Czujnik zderzenia bocznego lewego - awaria",
        ["B1000"] = "ECU - blad wewnetrzny",
        ["B1200"] = "Awaria obwodu swiatla klimatyzacji",
        ["B1318"] = "Niskie napiecie akumulatora",
        ["B1342"] = "ECU nie zaprogramowany",
        ["B1600"] = "Blad PATS - klucz niezaprogramowany",
        ["B2799"] = "Immobilizer - brak komunikacji z kluczem",

        // Chassis
        ["C0035"] = "Czujnik predkosci kola lewego przedniego - awaria",
        ["C0040"] = "Czujnik predkosci kola prawego przedniego - awaria",
        ["C0045"] = "Czujnik predkosci kola lewego tylnego - awaria",
        ["C0050"] = "Czujnik predkosci kola prawego tylnego - awaria",
        ["C0060"] = "ABS - awaria elektrozaworu lewego przedniego",
        ["C0065"] = "ABS - awaria elektrozaworu prawego przedniego",
        ["C0070"] = "ABS - awaria elektrozaworu lewego tylnego",
        ["C0075"] = "ABS - awaria elektrozaworu prawego tylnego",
        ["C0100"] = "ABS - pompa - awaria",
        ["C0110"] = "Modul pompy ABS - niskie napiecie",
        ["C0131"] = "ABS/TCS - blad konfiguracji",
        ["C0242"] = "Czujnik kata skretu - awaria",
        ["C0265"] = "Modul ABS/ESP - awaria wewnetrzna przekaznika",
        ["C0300"] = "Czujnik obrotu kola tylnego - awaria",

        // Network/Communication
        ["U0001"] = "Magistrala CAN HS - awaria",
        ["U0002"] = "Magistrala CAN HS - off bus",
        ["U0003"] = "Magistrala CAN HS - nadmiar bledow",
        ["U0073"] = "Magistrala sterujaca - off bus",
        ["U0100"] = "Brak komunikacji z ECM/PCM",
        ["U0101"] = "Brak komunikacji z TCM (skrzynia)",
        ["U0121"] = "Brak komunikacji z ABS",
        ["U0122"] = "Brak komunikacji z VSC (ESP)",
        ["U0126"] = "Brak komunikacji z czujnikiem kata skretu",
        ["U0129"] = "Brak komunikacji z hamulcem parkingowym",
        ["U0140"] = "Brak komunikacji z modulem nadwozia (BCM)",
        ["U0151"] = "Brak komunikacji z modulem SRS (airbag)",
        ["U0155"] = "Brak komunikacji z klastrem zegarow",
        ["U0164"] = "Brak komunikacji z modulem klimatyzacji",
        ["U0167"] = "Brak komunikacji z immobilizerem",
        ["U0184"] = "Brak komunikacji z radiem",
        ["U0195"] = "Brak komunikacji z modulem kurtyn powietrznych",
        ["U0401"] = "Nieprawidlowe dane z ECM",
        ["U0416"] = "Nieprawidlowe dane ze sterownika skrzyni",
        ["U0426"] = "Nieprawidlowe dane z czujnika kata skretu",
    };
}
